// 页面删减action
export const DOA = {
  ADD_PAGE: 'H5PAGE_ADD_PAGE',
  DEL_PAGE: 'H5PAGE_DEL_PAGE'
};
// modules action
export const MODULES = {
  ADD: 'H5PAGE_ADD_MODULE'
};
// 设置style action
export const SET_STYLES = {
  SET_BAK_COLOR: 'H5PAGE_SET_BAK_COLOR',
  SET_BAK_IMAGE: 'H5PAGE_SET_BAK_IMAGE',
  SET_WIDTH: 'H5PAGE_SET_WIDTH',
  SET_HEIGHT: 'H5PAGE_SET_HEIGHT'
};
// 设置状态 action
export const SET_STATUS = {
  TOGGLE_SETTING_PANEL: 'H5PAGE_TOGGLE_SETTING_PANEL',
  TOGGLE_BAKCOLOR_INPUT: 'H5PAGE_TOGGLE_BAKCOLOR_INPUT'
};
