// 页面删减action
export const DOA = {
  ADD_PAGE: 'ADD_PAGE',
  DEL_PAGE: 'DEL_PAGE'
};
// 设置style action
export const SET_STYLES = {
  SET_BAK_COLOR: 'SET_BAK_COLOR',
  SET_BAK_IMAGE: 'SET_BAK_IMAGE',
  SET_WIDTH: 'SET_WIDTH',
  SET_HEIGHT: 'SET_HEIGHT'
};
// 设置状态 action
export const SET_STATUS = {
  TOGGLE_SETTING_PANEL: 'TOGGLE_SETTING_PANEL',
  TOGGLE_BAKCOLOR_INPUT: 'TOGGLE_BAKCOLOR_INPUT'
};
