export const DOA_DEL = 'DOA_DEL';

export const SET_TEXT = 'TEXTAREA_SET_TEXT';
export const SET_FONTSIZE = 'TEXTAREA_SET_FONTSIZE';

export const TOGGLE_TEXT_INPUT = 'TEXTAREA_TOGGLE_TEXT_INPUT';
export const TOGGLE_SETTING_PANEL = 'TEXTAREA_TOGGLE_SETTING_PANEL';

export const SET_COORDINATE = 'TEXTAREA_SET_COORDINATE';
